
mover : inventario catalogo muestra resultados emision calidad dependencias
	mv inventario.png catalogo.png ingreso_muestras.png recoleccion_resultados.png emision_certificados.png  control_calidad.png dependencias_secuenciales.png /Users/jaumaf/.devs/rodam/docs/source/assets/

inventario :
	plantuml inventario.uml

catalogo :
	plantuml catalogo.uml

muestra :	
	plantuml ingreso_muestras.uml

resultados :
	plantuml recoleccion_resultados.uml

emision :
	plantuml emision_certificados.uml

calidad :
	plantuml control_calidad.uml

dependencias :
	plantuml dependencias_secuenciales.uml
