mover : lectura asociaciones especificacion
	mv lectura.png asociaciones.png especificacion.png certificado.png  /Volumes/Polyphemus/jaumaf/.devs/docs-laboratorio/docs/source/assets/
lectura : 
	dot -Tpng lectura.dot  > lectura.png

asociaciones :
	dot -Tpng asociaciones.dot  > asociaciones.png

especificacion :
	dot -Tpng especificacion.dot > especificacion.png

certificado :
	dot -Tpng certificado.uml > certificado.png
