<map version="0.9.0">
<node TEXT="casos" COLOR="#fdf6e3" BACKGROUND_COLOR="#839496" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_1222680865" CREATED="1680275846537" MODIFIED="1680275865541" ICON_SIZE="12 pt" HGAP_QUANTITY="14 pt" VSHIFT_QUANTITY="-29.25 pt">
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<node TEXT="desigualdad" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_1542268870" CREATED="1680275880656" MODIFIED="1680275948119" ICON_SIZE="12 pt">
<icon BUILTIN="button_ok" src="button_ok.svg" height="16"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="valor numerico" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_1066156097" CREATED="1680275885878" MODIFIED="1680275951059" ICON_SIZE="12 pt">
<icon BUILTIN="button_ok" src="button_ok.svg" height="16"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="presencia/ausencia" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_78991496" CREATED="1680275913013" MODIFIED="1680275954591" ICON_SIZE="12 pt">
<icon BUILTIN="button_ok" src="button_ok.svg" height="16"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="concepto/cualitativo" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_327391868" CREATED="1680275924926" MODIFIED="1680275959183" ICON_SIZE="12 pt">
<icon BUILTIN="button_ok" src="button_ok.svg" height="16"/>
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="rango" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_690028657" CREATED="1680275933514" MODIFIED="1680275935738" ICON_SIZE="12 pt">
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="acciones" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_1491307308" CREATED="1680275938231" MODIFIED="1680275939643" ICON_SIZE="12 pt">
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
<node TEXT="...(etc)" COLOR="#fdf6e3" BACKGROUND_COLOR="#93a1a1" STYLE="bubble" SHAPE_HORIZONTAL_MARGIN="11" SHAPE_HORIZONTAL_MARGIN_QUANTITY="8 pt" SHAPE_VERTICAL_MARGIN="7" SHAPE_VERTICAL_MARGIN_QUANTITY="5 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.9 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#f0f0f0" BORDER_DASH_LIKE_EDGE="true" BORDER_DASH="SOLID" ID="ID_361696593" CREATED="1684873685906" MODIFIED="1684873696970" ICON_SIZE="12 pt">
<edge STYLE="bezier" COLOR="#93a1a1" WIDTH="3" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="11" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</node>
</node>
</map>